In [28]:
import pandas as pd
import numpy as np
import os
import re

In [2]:
PATH_MOVIELENS = os.path.join('..','dataset','MovieLens')

In [3]:
movielens = pd.read_csv(os.path.join(PATH_MOVIELENS,'movies.csv'))
movielens.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
tmdb = pd.read_csv('../dataset/processed/movies_df_clean.csv')
tmdb.head()

,movie_id,budget,homepage,original_title,popularity,production_companies,production_countries,release_date,revenue,runtime,...,tagline,title,vote_average,vote_count,overview_clean,genres_clean,cast_clean,crew_clean,keywords_clean,original_language_full
0,19995,237000000,http://www.avatarmovie.com/,Avatar,150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,...,Enter the World of Pandora.,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...","Fantasy, Science Fiction, Action, Adventure","Sam Worthington, Zoe Saldana, Sigourney Weave...",Director: James Cameron,"space war, future, love affair, culture clash...",English
1,285,300000000,http://disney.go.com/disneypictures/pirates/,Pirates of the Caribbean: At World's End,139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,...,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"Captain Barbossa, long believed to be dead, ha...","Fantasy, Action, Adventure","Johnny Depp, Orlando Bloom, Keira Knightley, ...",Director: Gore Verbinski,"ocean, alliance, afterlife, traitor, east ind...",English
2,206647,245000000,http://www.sonypictures.com/movies/spectre/,Spectre,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,...,A Plan No One Escapes,Spectre,6.3,4466,A cryptic message from Bond’s past sends him o...,"Crime, Action, Adventure","Daniel Craig, Christoph Waltz, Léa Seydoux, R...",Director: Sam Mendes,"british secret service, mi6, sequel, based on...",English
3,49026,250000000,http://www.thedarkknightrises.com/,The Dark Knight Rises,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,...,The Legend Ends,The Dark Knight Rises,7.6,9106,Following the death of District Attorney Harve...,"Drama, Crime, Thriller, Action","Christian Bale, Michael Caine, Gary Oldman, A...",Director: Christopher Nolan,"burglar, flood, crime fighter, dc comics, hos...",English
4,49529,260000000,http://movies.disney.com/john-carter,John Carter,43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,...,"Lost in our world, found in another.",John Carter,6.1,2124,"John Carter is a war-weary, former military ca...","Science Fiction, Action, Adventure","Taylor Kitsch, Lynn Collins, Samantha Morton,...",Director: Andrew Stanton,"mars civilization, alien, medallion, superhum...",English

In [6]:
import re

In [31]:
movielens['title_clean'] =  movielens['title'].apply(lambda x : re.split(pattern = r' \(\d{4}\)',string=x)[0].lower().strip())

In [36]:
tmdb['title_clean'] = tmdb['title'].str.strip().str.lower()

In [51]:
tmdb[['title_clean','movie_id']].merge(movielens,on='title_clean',how='inner').rename(columns = {'movie_id':'tmdb_movieId',
                                                                                                 'movieId':'movieLens_movieId'})

,title_clean,tmdb_movieId,movieLens_movieId,title,genres
0,avatar,19995,72998,Avatar (2009),Action|Adventure|Sci-Fi|IMAX
1,pirates of the caribbean: at world's end,285,53125,Pirates of the Caribbean: At World's End (2007),Action|Adventure|Comedy|Fantasy
2,spectre,206647,136020,Spectre (2015),Action|Adventure|Crime
3,spectre,206647,161268,Spectre (1977),Horror
4,john carter,49529,93363,John Carter (2012),Action|Adventure|Sci-Fi|IMAX
...,...,...,...,...,...
4368,primer,14337,8914,Primer (2004),Drama|Sci-Fi
4369,newlyweds,72766,91829,Newlyweds (2011),Drama
4370,"signed, sealed, delivered",231617,164791,"Signed, Sealed, Delivered (2013)",Comedy|Drama
4371,shanghai calling,126186,101294,Shanghai Calling (2012),Comedy|Drama|Romance
4372,my date with drew,25975,34767,My Date with Drew (2004),Comedy|Documentary|Romance

In [52]:
matched_movies =  (tmdb[['title_clean','movie_id']]
                    .merge(movielens,on='title_clean',how='inner')
                    .rename(columns = {'movie_id':'tmdb_movieId','movieId':'movieLens_movieId'}))

In [55]:
# dictionary of {tmdb_movieId : movieLens_movieId}
# dict(zip(matched_movies['tmdb_movieId'],matched_movies['movieLens_movieId']))

{19995: 72998,
 285: 53125,
 206647: 161268,
 49529: 93363,
 559: 52722,
 38757: 138616,
 99861: 122892,
 767: 69844,
 209112: 136864,
 1452: 46530,
 10764: 63113,
 58: 45722,
 57201: 121693,
 49521: 103042,
 1865: 86880,
 122917: 118696,
 20662: 191469,
 254: 41569,
 597: 181653,
 271110: 122920,
 44833: 94018,
 135397: 117529,
 37724: 96079,
 558: 8636,
 68721: 102125,
 12155: 178635,
 36668: 45499,
 62211: 103141,
 8373: 69526,
 91314: 112370,
 102382: 110553,
 20526: 82461,
 49013: 87876,
 44912: 87430,
 10193: 78499,
 534: 68791,
 168259: 130634,
 72190: 103249,
 127585: 111362,
 54138: 102445,
 81005: 101025,
 64682: 121618,
 9543: 78105,
 68726: 103228,
 38356: 87520,
 217: 59615,
 105864: 136016,
 62177: 148590,
 188927: 135569,
 10681: 60069,
 5174: 54648,
 14161: 72378,
 17979: 196729,
 76757: 113345,
 258489: 160563,
 411: 185231,
 246655: 122924,
 155: 130219,
 14160: 68954,
 1726: 167296,
 44826: 90866,
 8487: 2701,
 297761: 135536,
 2698: 53993,
 137113: 111759,
 9804: 208,
 14869: 70336,
 150540: 205277,
 278927: 137857,
 10138: 77561,
 58595: 94780,
 102651: 111659,
 119450: 112623,
 79698: 188361,
 64686: 106491,
 100402: 110102,
 158852: 132046,
 177572: 115617,
 82690: 97913,
 47933: 135567,
 10191: 76093,
 296: 6537,
 118340: 112852,
 157336: 109487,
 27205: 79132,
 315011: 163056,
 49538: 87232,
 131634: 135133,
 27022: 172411,
 503: 45442,
 241259: 158813,
 810: 53121,
 68735: 122890,
 87101: 120799,
 676: 4310,
 1858: 53996,
 1966: 8977,
 675: 54001,
 674: 40815,
 8960: 60074,
 6479: 56174,
 118: 30793,
 2062: 50872,
 272: 33794,
 10527: 62999,
 18360: 68793,
 2080: 68319,
 109445: 118818,
 76338: 106072,
 76341: 122882,
 13448: 68554,
 10195: 86332,
 13053: 147539,
 19585: 70697,
 57165: 93766,
 62213: 94478,
 177677: 111781,
 5559: 55768,
 49444: 87222,
 956: 45186,
 117251: 103339,
 50321: 85261,
 11619: 48982,
 266647: 130450,
 82703: 109846,
 652: 7458,
 80321: 95105,
 36669: 5872,
 43074: 160080,
 95: 1917,
 2310: 55995,
 140300: 149406,
 56292: 91630,
 81188: 98243,
 7552: 42011,
 147441: 116887,
 13475: 68358,
 557: 5349,
 82702: 112175,
 205584: 152063,
 10048: 34334,
 13183: 60684,
 944: 1918,
 1927: 6534,
 72559: 101076,
 7364: 175753,
 2114: 4446,
 1771: 88140,
 8619: 6947,
 65759: 91386,
 267935: 186197,
 281957: 139385,
 77950: 103755,
 44896: 84944,
 270946: 117851,
 9502: 59784,
 102899: 122900,
 101299: 106487,
 228161: 199556,
 74: 64997,
 8961: 6548,
 417859: 130758,
 27576: 79293,
 86834: 150140,
 673: 8368,
 6972: 63853,
 82700: 102880,
 10567: 3615,
 181533: 119155,
 38055: 81564,
 49524: 103655,
 22: 6539,
 131631: 116823,
 172385: 110655,
 58574: 91542,
 18823: 76175,
 861: 95875,
 415: 1562,
 955: 3623,
 87827: 97938,
 1250: 51077,
 324668: 160438,
 9471: 6503,
 70981: 94864,
 10996: 5480,
 68724: 103253,
 97020: 108945,
 7459: 59037,
 42888: 82499,
 37834: 79185,
 75612: 153304,
 1895: 33493,
 1894: 5378,
 585: 4886,
 1893: 2628,
 12100: 5420,
 98566: 113348,
 49047: 104841,
 9619: 1438,
 308531: 159690,
 166424: 122902,
 1593: 46972,
 254128: 132796,
 714: 1722,
 163: 8984,
 787: 33679,
 262500: 130490,
 38745: 173873,
 40805: 124039,
 53182: 109673,
 13700: 7374,
 39254: 90249,
 1639: 1556,
 80274: 106002,
 1571: 53972,
 10204: 161474,
 8489: 5009,
 2048: 8644,
 1495: 33162,
 10137: 3157,
 286217: 134130,
 1635: 196745,
 24113: 4268,
 98: 8132,
 180: 5445,
 672: 5816,
 36557: 49272,
 869: 4643,
 280: 589,
 11322: 149938,
 4982: 55765,
 36955: 380,
 39451: 82852,
 9268: 786,
 68718: 99114,
 2059: 8972,
 2486: 49649,
 16523: 71745,
 116711: 102720,
 9946: 3113,
 1372: 49530,
 414: 153,
 563: 1676,
 83542: 97752,
 41216: 80615,
 314: 8666,
 184315: 170433,
 9016: 5882,
 18162: 69278,
 138103: 112897,
 257088: 147847,
 10214: 31698,
 205775: 117466,
 22972: 74795,
 3131: 5956,
 9408: 53460,
 855: 5010,
 37786: 78174,
 150689: 205873,
 12: 6377,
 68737: 119655,
 1995: 4367,
 157353: 110730,
 331: 4638,
 61791: 88744,
 10733: 7379,
 1408: 15,
 32657: 74530,
 863: 3114,
 44048: 198261,
 5175: 4701,
 2655: 3798,
 22794: 71264,
 8355: 69644,
 4327: 206899,
 10674: 90620,
 7446: 61132,
 1572: 165,
 10528: 188911,
 271969: 122888,
 10865: 4366,
 258509: 158428,
 2253: 64983,
 10661: 59900,
 257344: 166952,
 644: 4370,
 686: 193189,
 9383: 3826,
 179: 196397,
 76285: 104074,
 1996: 6564,
 291805: 159093,
 10003: 175505,
 1535: 4901,
 2067: 3354,
 46195: 130008,
 2277: 3156,
 10357: 194528,
 8665: 5479,
 9387: 89190,
 921: 33660,
 4464: 6565,
 664: 7781,
 8358: 4022,
 9836: 49274,
 9772: 1608,
 161: 4963,
 52451: 160908,
 76492: 97225,
 4523: 56152,
 59961: 92507,
 10481: 3991,
 59108: 90717,
 9798: 2353,
 22897: 73015,
 298: 53322,
 7484: 133411,
 157350: 108190,
 853: 4223,
 9593: 485,
 1904: 41571,
 51052: 91414,
 297: 2340,
 9884: 5093,
 16858: 2971,
 62764: 139026,
 22538: 79702,
 12107: 3821,
 9637: 5419,
 49049: 96737,
 9339: 45672,
 16281: 3016,
 8247: 58025,
 11253: 57640,
 1949: 126579,
 310: 6373,
 954: 648,
 70160: 91500,
 364: 1377,
 7518: 45431,
 11544: 5444,
 9986: 49647,
 8656: 1876,
 146216: 103810,
 55301: 91671,
 109418: 104218,
 11665: 60126,
 6964: 7149,
 11324: 74458,
 12193: 64032,
 9928: 32031,
 754: 1573,
 10202: 65088,
 4147: 5464,
 50546: 85367,
 1701: 1552,
 13027: 62081,
 2289: 7162,
 9574: 1702,
 11618: 208395,
 2300: 673,
 8834: 195313,
 228150: 115210,
 6068: 1894,
 41515: 83177,
 9023: 5389,
 38317: 87867,
 2157: 1831,
 161795: 188899,
 159824: 142997,
 49948: 3159,
 9822: 2430,
 9705: 4344,
 12159: 2297,
 9678: 3979,
 75: 1391,
 330770: 155074,
 9433: 162214,
 19959: 71530,
 11973: 4033,
 11228: 94491,
 77951: 116213,
 5491: 3593,
 10715: 6946,
 10197: 73000,
 9562: 6959,
 9447: 2384,
 274854: 135532,
 8870: 3981,
 9992: 50162,
 76649: 110968,
 8587: 203222,
 72545: 92681,
 109451: 105468,
 9533: 5630,
 2023: 7324,
 71880: 90890,
 309809: 195403,
 328111: 135436,
 93456: 103335,
 953: 100046,
 9693: 48774,
 36657: 3793,
 8909: 151420,
 1824: 7293,
 2976: 52975,
 11026: 8815,
 332: 2720,
 75656: 102903,
 38365: 79134,
 15189: 66304,
 11678: 3999,
 6538: 56788,
 10555: 8907,
 1125: 49824,
 4551: 32019,
 612: 41997,
 9567: 6213,
 37821: 119126,
 203801: 138036,
 2539: 27808,
 9297: 46948,
 3172: 4844,
 6520: 168,
 1439: 3155,
 37958: 90888,
 2026: 202960,
 7450: 3745,
 11375: 6484,
 9425: 146262,
 25769: 73168,
 23685: 4158,
 11866: 27837,
 9741: 3994,
 211672: 135887,
 23629: 187005,
 8688: 2126,
 10153: 1779,
 153518: 157340,
 8676: 57951,
 20829: 66509,
 9718: 46970,
 10808: 4368,
 197: 110,
 25: 40278,
 10477: 205064,
 6947: 194600,
 3050: 2135,
 2675: 126008,
 809: 8360,
 920: 45517,
 4806: 2724,
 7451: 5507,
 3595: 832,
 16869: 68157,
 879: 3489,
 1573: 1370,
 9257: 6595,
 1903: 4975,
 9697: 45730,
 395: 8810,
 23398: 73042,
 10590: 5152,
 117263: 101362,
 200: 2393,
 44943: 85131,
 587: 7147,
 10395: 148078,
 57212: 91126,
 33909: 80590,
 49017: 114795,
 2270: 110179,
 978: 1619,
 3132: 187431,
 8814: 37380,
 8427: 5803,
 52520: 91974,
 80585: 95307,
 10592: 5107,
 49021: 89840,
 11535: 5522,
 10550: 5609,
 11258: 1752,
 12610: 4719,
 59981: 111439,
 201088: 120637,
 5137: 8865,
 3093: 44759,
 107846: 105653,
 20352: 79091,
 11517: 20,
 214756: 135861,
 26428: 74624,
 9824: 2723,
 48988: 85022,
 300673: 151777,
 12113: 62374,
 38778: 79428,
 72331: 95207,
 1844: 2605,
 857: 2028,
 136797: 109850,
 3981: 4018,
 425: 5218,
 6171: 140152,
 72976: 98154,
 568: 150,
 82695: 202497,
 9489: 2424,
 12133: 60756,
 41733: 81537,
 227306: 118702,
 5551: 3827,
 9350: 434,
 9208: 54121,
 4244: 199255,
 1852: 46974,
 11820: 7154,
 345: 2712,
 196867: 175231,
 256591: 129354,
 59962: 93326,
 36648: 8985,
 1880: 98239,
 9440: 1810,
 71679: 96691,
 10483: 61248,
 11983: 3998,
 550: 2959,
 11170: 49793,
 9292: 7000,
 10783: 3975,
 100241: 108689,
 257: 122711,
 9947: 31221,
 189: 113573,
 12618: 2906,
 253412: 142448,
 1427: 48997,
 818: 5481,
 16577: 72209,
 329: 480,
 12160: 383,
 9331: 349,
 300168: 134775,
 9072: 172427,
 3536: 3555,
 12138: 4159,
 273248: 128360,
 9955: 52245,
 50359: 178567,
 1271: 51662,
 693: 30825,
 14306: 65230,
 11199: 51575,
 9982: 197827,
 210577: 112556,
 710: 200790,
 10708: 6338,
 136400: 103883,
 10992: 4386,
 2642: 5957,
 8916: 2294,
 19899: 71668,
 2119: 1100,
 9641: 42009,
 38167: 80551,
 39514: 81229,
 9563: 3173,
 1538: 8798,
 9334: 5313,
 11128: 8908,
 75780: 99112,
 8914: 2722,
 39538: 89470,
 10628: 6013,
 14836: 66097,
 8645: 133757,
 9509: 123178,
 9384: 7325,
 9279: 1359,
 1487: 196223,
 77174: 96281,
 9620: 7163,
 3512: 204,
 137094: 108188,
 274479: 202425,
 267860: 152079,
 8078: 1690,
 7485: 51935,
 6435: 2316,
 137106: 108932,
 10040: 32296,
 6278: 5463,
 82682: 99728,
 17610: 69436,
 22954: 72733,
 16995: 68159,
 16558: 67193,
 9849: 2498,
 5820: 181531,
 16866: 72701,
 201: 5944,
 11775: 6873,
 87825: 96693,
 12201: 176795,
 9932: 5900,
 13389: 61697,
 8838: 1833,
 786: 3897,
 9513: 46337,
 11679: 33158,
 38321: 86835,
 14411: 6536,
 8413: 1590,
 10052: 110562,
 9664: 48319,
 10384: 177775,
 137321: 109191,
 11260: 60516,
 9009: 34143,
 11374: 2567,
 2309: 65685,
 210860: 125914,
 2312: 57326,
 9839: 6886,
 13922: 34536,
 293660: 122904,
 9713: 2306,
 190859: 114662,
 257445: 144620,
 9007: 36525,
 1370: 2404,
 4942: 58839,
 347969: 148652,
 24438: 72919,
 35791: 80363,
 72431: 92234,
 1813: 1645,
 87428: 96616,
 8840: 653,
 10589: 8968,
 71676: 92938,
 1722: 4727,
 11358: 26309,
 13: 356,
 6477: 56176,
 1597: 3948,
 10530: 48,
 1924: 140417,
 8488: 31685,
 10603: 1588,
 109424: 105504,
 35056: 76293,
 8839: 158,
 7303: 5943,
 8963: 161,
 9315: 37727,
 8984: 225,
 795: 1835,
 24: 6874,
 11353: 2770,
 393: 7438,
 9618: 4673,
 9374: 3258,
 8584: 3624,
 2320: 494,
 58224: 87483,
 175574: 106240,
 8818: 1416,
 8195: 2278,
 116149: 117887,
 10632: 194877,
 12117: 208158,
 1792: 7150,
 13260: 58156,
 3580: 63062,
 12123: 836,
 9833: 186219,
 4517: 55274,
 16072: 6186,
 34314: 184949,
 19724: 69304,
 145220: 110297,
 14623: 8782,
 42297: 83086,
 802: 2729,
 36586: 5254,
 11321: 64716,
 70074: 91483,
 9621: 39231,
 1819: 45726,
 8536: 2641,
 8046: 6587,
 1717: 48326,
 479: 203244,
 9444: 6516,
 11456: 4885,
 261023: 136018,
 3683: 48783,
 22803: 71838,
 285923: 52281,
 39437: 2314,
 1950: 52724,
 640: 164314,
 97630: 98961,
 11631: 60397,
 32856: 74450,
 8741: 166237,
 1850: 3174,
 524: 16,
 26389: 74851,
 11817: 6294,
 2123: 3752,
 9969: 140992,
 808: 4306,
 8367: 1027,
 9390: 1393,
 72105: 95441,
 2898: 1784,
 10312: 2431,
 109443: 107348,
 2022: 5449,
 37686: 87306,
 462: 3408,
 9919: 6155,
 187017: 112138,
 10201: 64969,
 302699: 160271,
 9441: 2432,
 274167: 149352,
 224141: 165399,
 388: 44199,
 2112: 205345,
 10329: 160,
 74465: 91653,
 13811: 67197,
 6877: 44004,
 50646: 88163,
 13673: 8978,
 60308: 89492,
 6950: 292,
 225574: 122569,
 13836: 70305,
 752: 44191,
 6038: 6156,
 9975: 43869,
 12103: 4814,
 60304: 100163,
 2251: 5364,
 46529: 85056,
 231: 40583,
 228326: 115664,
 9754: 43871,
 66: 1459,
 4421: 1586,
 2649: 166735,
 588: 45081,
 216282: 114033,
 306: 420,
 928: 2004,
 1577: 8861,
 9801: 8969,
 2116: 205423,
 9624: 7725,
 4599: 8362,
 22832: 72489,
 10390: 2861,
 9879: 762,
 38579: 77665,
 44603: 81512,
 11892: 5312,
 9691: 23,
 1248: 50804,
 10782: 6263,
 9573: 5506,
 10061: 849,
 316152: 157338,
 13498: 31867,
 241554: 129937,
 2252: 55118,
 11968: 37853,
 38319: 87529,
 69668: 185063,
 9770: 1667,
 11212: 5096,
 38363: 160768,
 9923: 202221,
 11863: 132,
 18501: 173551,
 109491: 100487,
 9275: 5265,
 329833: 148888,
 12634: 178563,
 10416: 3326,
 47327: 84942,
 15268: 66639,
 10796: 172423,
 1900: 186707,
 89: 1291,
 96724: 192449,
 198184: 120466,
 4547: 5266,
 53953: 122817,
 6415: 2890,
 181283: 130956,
 9896: 121705,
 167: 4874,
 11232: 4992,
 1636: 7708,
 5176: 54997,
 260346: 120635,
 1389: 195897,
 7504: 68522,
 8592: 2616,
 11091: 4867,
 593: 5881,
 5393: 50149,
 9095: 92,
 8874: 1569,
 11467: 4639,
 320: 5388,
 199: 1356,
 20533: 78467,
 10684: 647,
 1624: 1485,
 325789: 161127,
 113464: 147887,
 82675: 96861,
 4256: 6888,
 1493: 4025,
 88751: 192003,
 10731: 144504,
 9869: 3256,
 4379: 33499,
 146233: 104879,
 2034: 4776,
 926: 3175,
 4248: 4388,
 36647: 143900,
 7214: 31225,
 1537: 5293,
 9360: 1499,
 6282: 3825,
 508: 6942,
 768: 4865,
 10478: 852,
 27983: 40962,
 9981: 33495,
 15045: 30883,
 7737: 55232,
 232672: 111617,
 17379: 91666,
 82525: 176149,
 9759: 8860,
 9486: 6550,
 841: 2021,
 4688: 54190,
 4148: 65130,
 2207: 43936,
 9381: 61350,
 9304: 719,
 20856: 70282,
 9826: 167886,
 21355: 4031,
 10858: 14,
 9457: 1762,
 12412: 61991,
 13184: 61465,
 2185: 6601,
 6639: 56001,
 38153: 1055,
 58233: 90522,
 116977: 120222,
 68734: 176905,
 27573: 125179,
 819: 1061,
 1369: 2402,
 10895: 199540,
 10935: 5184,
 834: 42738,
 228066: 141004,
 711: 4019,
 10468: 3534,
 10027: 177193,
 37233: 183913,
 37950: 79588,
 64688: 93510,
 509: 2671,
 7443: 3751,
 5966: 7173,
 11066: 152266,
 136795: 172679,
 8095: 197465,
 87826: 97836,
 11560: 5282,
 709: 2990,
 49730: 123320,
 2749: 4167,
 9607: 546,
 1830: 36529,
 79: 146138,
 54054: 92264,
 228967: 196477,
 65: 5810,
 280391: 189747,
 745: 197499,
 49527: 91978,
 168672: 106916,
 18240: 194508,
 10398: 185197,
 165: 2011,
 240832: 111360,
 216015: 125916,
 12279: 6566,
 11007: 7395,
 193756: 107069,
 259693: 159858,
 10184: 66203,
 4257: 44972,
 4234: 3273,
 196: 2012,
 257091: 131013,
 6114: 202033,
 24803: 70293,
 109410: 101895,
 100042: 116977,
 9036: 43917,
 257211: 140110,
 323675: 151315,
 9361: 167876,
 1677: 8958,
 187: 32587,
 7461: 58103,
 16538: 67087,
 9889: 4890,
 820: 3386,
 11565: 43558,
 16996: 68135,
 296098: 143385,
 8007: 108852,
 32823: 78209,
 4380: 8916,
 11551: 1920,
 10336: 1591,
 11362: 128295,
 48138: 84601,
 227159: 117590,
 68179: 100611,
 1579: 48304,
 34851: 79057,
 9930: 6308,
 1586: 7347,
 10761: 59333,
 209451: 112316,
 4970: 6952,
 11831: 1693,
 9096: 2822,
 10641: 3824,
 11172: 51084,
 39513: 84772,
 41446: 86295,
 8224: 2505,
 225886: 112788,
 10385: 3299,
 55779: 88932,
 10154: 2805,
 10647: 3969,
 11431: 155462,
 8457: 58655,
 188161: 111743,
 38357: 207151,
 10060: 40574,
 1833: 40826,
 10391: 3857,
 1921: 43567,
 203: 8042,
 11858: 516,
 62835: 89087,
 18937: 1881,
 13536: 5563,
 15556: 2445,
 10718: 7175,
 11062: 100,
 10802: 193,
 1887: 48700,
 6071: 41585,
 10461: 3947,
 12704: 4123,
 10315: 72226,
 16643: 5324,
 2687: 6734,
 11025: 7453,
 8849: 8948,
 78698: 92335,
 24418: 72165,
 7288: 6763,
 14655: 63481,
 24575: 3403,
 10366: 2807,
 ...}

In [57]:
movieId_lookup = matched_movies[['tmdb_movieId','movieLens_movieId']]

In [61]:
movieId_lookup.to_csv('../dataset/processed/movieId_lookup.csv',index=False)