In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
PATH_MOVIELENS = os.path.join('..','dataset','MovieLens')

In [3]:
movies = pd.read_csv(os.path.join(PATH_MOVIELENS,'movies.csv'))
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
ratings = pd.read_csv(os.path.join(PATH_MOVIELENS,'ratings.csv'))
ratings.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [5]:
ratings.shape

(25000095, 4)

In [6]:
genometags = pd.read_csv(os.path.join(PATH_MOVIELENS,'genome-tags.csv'))
genometags.head()

   tagId           tag
0      1           007
1      2  007 (series)
2      3  18th century
3      4         1920s
4      5         1930s

In [8]:
genometags.shape

(1128, 2)

In [7]:
tags = pd.read_csv(os.path.join(PATH_MOVIELENS,'tags.csv'))
tags.head()

   userId  movieId               tag   timestamp
0       3      260           classic  1439472355
1       3      260            sci-fi  1439472256
2       4     1732       dark comedy  1573943598
3       4     1732    great dialogue  1573943604
4       4     7569  so bad it's good  1573943455

In [8]:
tags.shape

(1093360, 4)

In [9]:
genome_scores = pd.read_csv(os.path.join(PATH_MOVIELENS,'genome-scores.csv'))
genome_scores.head()

   movieId  tagId  relevance
0        1      1    0.02875
1        1      2    0.02375
2        1      3    0.06250
3        1      4    0.07575
4        1      5    0.14075

In [10]:
genome_scores.shape

(15584448, 3)

In [12]:
movies.shape[0]* genometags.shape[0]

70413144

In [17]:
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
62418,209157,We (2018),Drama
62419,209159,Window of the Soul (2001),Documentary
62420,209163,Bad Poems (2018),Comedy|Drama
62421,209169,A Girl Thing (2001),(no genres listed)
62422,209171,Women of Devil's Island (1962),Action|Adventure|Drama

In [12]:
links = pd.read_csv(os.path.join(PATH_MOVIELENS,'links.csv'))
links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [23]:
movies[movies['title'].str.contains('Avatar')]

,movieId,title,genres
14102,72998,Avatar (2009),Action|Adventure|Sci-Fi|IMAX
19997,103676,My Avatar and Me (Min Avatar og mig) (2010),Documentary
46636,172851,Avatar: Creating the World of Pandora (2010),Documentary